- name: 'Copy file to server'
  tags: file,test
  copy: 
    src: test.txt
    dest: /var/log/
    owner: root
    group: root
    mode: 0644

  # Gather IP facts from your own ipify service endpoint with a custom timeout
  - name: Get my public IP
    community.general.ipify_facts:
      api_url: 'https://api.ipify.org/'
      timeout: 60
